title: "CHarles and Gamon"
description: ""
email: "info@charlesandgamon.com"
encoding: utf-8

#Outputting
permalink: pretty
markdown: kramdown
highlighter: rouge
timezone: "Australia/Melbourne"

# Build settings
defaults:
  - 
    scope:
      path: ""
    values:
      layout: default

# Excludes
exclude:
  - LICENSE
  - CNAME
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
 
 # Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

whitelist:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

kramdown:
  hard_wrap: false
  input: GFM

#sass:
  style: compressed